### ISSUE TITLE
Data should not be empty or the "fields" option should be included

### ISSUE THREAD

**Issue by hanthienhai** [jlhernando/index-coverage-extractor#1]
Hello, I meet erorr "There was an error running the script: Error: Data should not be empty or the "fields" option should be included" when extracting urls. Can you help fix this issue. 
Thank you very much!

**Comment by jlhernando** [comment]
Hi @hanthienhai, I've had a look and I think that issue happens because there are no sitemaps in your property. Hence the arrays are empty at the point of parsing which throws an error. I've updated the script to account for this. Let me know if you have further issues.

**Comment by hanthienhai** [comment]
Thank you, it's work perfectly!
