### ISSUE TITLE
Export Page indexing > All known pages Not Filter to Sitemaps

### ISSUE THREAD

**Issue by coseo638** [jlhernando/index-coverage-extractor#3]
Hello, The program runs very well. But I can only export urls from sitemap. I have reconfigured const sitemapExtract = false; The program cannot export the url anymore. 

I want to export the url according to **Page indexing > All known pages** Not **Filter to Sitemaps** as currently. Don't know if it can be done? 

![2024-01-06_8-42-07](https://github.com/jlhernando/index-coverage-extractor/assets/155712415/51cb2c84-b256-4a8f-bff7-4ab089a14836)

Thank you for everything. Wishing you and your family a nice day!

**Comment by jlhernando** [comment]
Sorry must have missed this. If you retry the script with the latest version you should get both the Pages section and the Sitemap section.
